build1:
  stage: build
  image: maven:3.8-openjdk-8-slim
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar

test1:
  stage: test
  image: docker:stable
  before_script:
    - echo "before"
    - echo $CI_COMMIT_SHA
  script:
    - ls -al
    - docker build -t https://harbor.sunvalley.com.cn/danya/necho/demo-0.0.2.jar:$CI_COMMIT_SHA .
    - docker images
    - docker login -u necho.duan -p iot123456abC harbor.sunvalley.com.cn
    - docker info
    - docker push  https://harbor.sunvalley.com.cn/danya/necho/demo-0.0.2.jar:$CI_COMMIT_SHA
    - echo "Do a test here"
    - echo "For example run a  test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy1:
  stage: deploy
  image: istio/kubectl:1.5.10
  script:
    - mkdir $HOME/.kube && cat $KUBE_CONFIG > $HOME/.kube/config
    - kubectl -n xiaopang patch deployment nginx-xiaopang-deployment -p '{"spec":{"template":{"spec":{"containers":[{"name":"nginx","image":"nginx:1.7.9","env":[{"name":"RESTART_TIME","value":"'$(date +%s)'"}]}]}}}}'
