image: busybox:latest

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"
  - whoami



after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"
  - ping -c 6 127.0.0.1

build1:
  stage: build
  script:
    - mvn package

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
    - ping -c 20 127.0.0.1