maven build:
  stage: build
  image: maven:3.8-openjdk-8-slim
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar

docker build and push:
  stage: test
  image: docker:stable
  before_script:
    - echo "before docker build and push "
    - echo $CI_COMMIT_SHA
  script:
    - ls -al
    - docker build -t harbor.sunvalley.com.cn/danya/demo-0.0.2.jar:$CI_COMMIT_SHA .
    ## - docker images
    - docker login -u necho.duan -p iot123456abF harbor.sunvalley.com.cn
    ## - docker info
    - docker push  harbor.sunvalley.com.cn/danya/demo-0.0.2.jar:$CI_COMMIT_SHA
    - echo " push success !"


do task:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

k8s deploy:
  stage: deploy
  image: istio/kubectl:1.5.10
  script:
    - mkdir $HOME/.kube && cat $KUBE_CONFIG > $HOME/.kube/config
    - export NAMESPACE=xiaopang
    - export REPLICAS=2
    - export IMAGE=harbor.sunvalley.com.cn/danya/demo-0.0.2.jar:$CI_COMMIT_SHA
    - envsubst < deploy.yaml | echo
    ## - kubectl -n xiaopang patch deployment nginx-xiaopang-deployment -p '{"spec":{"template":{"spec":{"containers":[{"name":"demon","image":harbor.sunvalley.com.cn/danya/demo-0.0.2.jar:$CI_COMMIT_SHA,"env":[{"name":"RESTART_TIME","value":"'$(date +%s)'"}]}]}}}}'
