image: maven:3.8-openjdk-8-slim

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"


build1:
  stage: build
  script:
    - mvn package -Dmaven.test.skip=true
    - java -jar target/demo-0.0.1-SNAPSHOT.jar

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a                                                                                                 test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy1:
  stage: deploy
  image: kubectl:v1.18.5
  script:
    - mkdir $HOME/.kube && cat $KUBE_CONFIG > $HOME/.kube/config
    - kubectl version
    - kubectl -n xiaopang patch deployment nginx -p '{"spec":{"template":{"spec":{"containers":[{"name":"nginx","env":[{"name":"RESTART_TIME","value":"'$(date +%s)'"}]}]}}}}'
